[package]
name = "my_os"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.26.0", features = ["alloc"], default-features = false }
uefi-services = "0.23.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort" 